### ISSUE TITLE
Publishing the extension on the markerplace

### ISSUE THREAD

**Issue by TheNouillet** [TheNouillet/symfony-vscode#18]

**Comment by oojacoboo** [comment]
Are there plans to do this and continue development?  VSCode desperately needs better Symfony support, especially for the service container.

**Comment by TheNouillet** [comment]
Hey,

I am pleasantly surprised by the fact that there is some demand for this extension ! I did let it down a bit for quite some time, so I'll get back to work. I am aiming for a release at the end of the month, with the latest features.

Thanks for the heads up !

**Comment by oojacoboo** [comment]
That's excellent news!  This is the key missing component for myself when it comes to using VSCode.  I'm speaking for others here, but I think a lot more people would choose to use VSCode with more Symfony component support.

**Comment by Tardog** [comment]
@TheNouillet Just chiming in to let you know that I would love to see better Symfony support in VSCode, too. Great to hear that work on this hasn't been abandoned.

Are you looking for help?

**Comment by TheNouillet** [comment]
@Tardog I just pushed a contribution manual here : https://github.com/TheNouillet/symfony-vscode/blob/develop/CONTRIBUTING.md . Creating issues will definitely help, especially considering the changes between versions 2 to 4 of Symfony, so more testing is welcome.

**Comment by oojacoboo** [comment]
@TheNouillet @Tardog please check out this: https://github.com/bmewburn/intelephense/issues/89

There appears to be a new "stubs" approach with this intellisense plugin, which IMO is the best one available for PHP.  It might be best to focus efforts on collaboration of a "stub" here instead of trying to duplicate efforts.

**Comment by Tardog** [comment]
@oojacoboo  I agree in that Intelephense provides high value for PHP development in VScode, and if there is an effort to provide DI container autocompletion through that plugin, it should be supported.

There already seems to be a working solution for Laravel. I haven't been able to test this yet, but looks promising. https://github.com/bmewburn/vscode-intelephense/issues/143

Can you clarify what you mean by "stub" in that context? How would you implement it?

**Comment by TheNouillet** [comment]
Hello,

The extension being **FINALLY** published [here](https://marketplace.visualstudio.com/items?itemName=TheNouillet.symfony-vscode), I close this issue.

For the discussion about the .phpstorm.meta, I consigned what we have [here](https://github.com/TheNouillet/symfony-vscode/issues/29).
