### ISSUE TITLE
PHP 7.2 Uncaught ReflectionException: Class CacheInterface not found

### ISSUE THREAD

**Issue by frenzymind** [TheNouillet/symfony-vscode#43]
Hello. I create skeleton project on local machine and get this error:

`PHP Fatal error:  During class fetch: Uncaught ReflectionException: Class Psr\SimpleCache\CacheInterface not found in /home/default/projects/symf_test/vendor/symfony/cache/Psr16Cache.php:27
Stack trace:
#0 /home/default/projects/symf_test/vendor/symfony/debug/DebugClassLoader.php(160): require('/home/default/p...')
#1 [internal function]: Symfony\Component\Debug\DebugClassLoader->loadClass('Symfony\\Compone...')
#2 [internal function]: spl_autoload_call('Symfony\\Compone...')
#3 /home/default/projects/symf_test/vendor/symfony/config/Resource/ClassExistenceResource.php(78): class_exists('Symfony\\Compone...')
#4 /home/default/projects/symf_test/vendor/symfony/framework-bundle/Console/Descriptor/Descriptor.php(307): Symfony\Component\Config\Resource\ClassExistenceResource->isFresh(0)
#5 /home/default/projects/symf_test/vendor/symfony/framework-bundle/Console/Descriptor/JsonDescriptor.php(239): Symfony\Bundle\FrameworkBundle\Console\Descriptor\Descriptor::getClassDescription('Symfony\\Compone...')
#6 /home/default/projects/symf_t in /home/default/projects/symf_test/vendor/symfony/cache/Psr16Cache.php on line 27
2019-07-15T11:52:21+08:00 [critical] Fatal Error: During class fetch: Uncaught ReflectionException: Class Psr\SimpleCache\CacheInterface not found in /home/default/projects/symf_test/vendor/symfony/cache/Psr16Cache.php:27
Stack trace:
#0 /home/default/projects/symf_test/vendor/symfony/debug/DebugClassLoader.php(160): require('/home/default/p...')
#1 [internal function]: Symfony\Component\Debug\DebugClassLoader->loadClass('Symfony\\Compone...')
#2 [internal function]: spl_autoload_call('Symfony\\Compone...')
#3 /home/default/projects/symf_test/vendor/symfony/config/Resource/ClassExistenceResource.php(78): class_exists('Symfony\\Compone...')
#4 /home/default/projects/symf_test/vendor/symfony/framework-bundle/Console/Descriptor/Descriptor.php(307): Symfony\Component\Config\Resource\ClassExistenceResource->isFresh(0)
#5 /home/default/projects/symf_test/vendor/symfony/framework-bundle/Console/Descriptor/JsonDescriptor.php(239): Symfony\Bundle\FrameworkBundle\Console\Descriptor\Descriptor::getClassDescription('Symfony\\Compone...')
#6 /home/default/projects/symf_t
`

what should I do here ?

**Comment by shyim** [comment]
Can you downgrade to PHP 7.2.19?

**Comment by frenzymind** [comment]
Yes, I downgrade php version to 7.2 and project start to work!
Thanks!
